# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"mySum": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://roiweinreb.github.io/hello/"

git_url = "https://github.com/roiweinreb/hello/tree/master/"

def custom_doc_links(name): return None
